spring:
  datasource:
    driverClassName: "com.mysql.cj.jdbc.Driver"
    url: jdbc:mysql://localhost:3306/geist_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: "root"
    password: "1234"
    continueOnError: true
  jpa:
    #For MySQL 8
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      EAGER_SERIALIZER_FETCH: false

server:
  error:
    include-message: always
    include-stacktrace: always


logging:
  level:
#    org.springframework.security: DEBUG
#    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

myapp:
  version: 21.03.2021