spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/style_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false"
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASS:}
#    continueOnError: true
    tomcat:
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
  jpa:
    # MySQL 8
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    # MySQL 5
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      EAGER_SERIALIZER_FETCH: false
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  error:
    include-message: always
    include-stacktrace: always

logging:
  level:
    bg.geist: debug
    #    root: warn
    org.springframework.web: error
    org.springframework.security: error
    org.hibernate: error
    org.hibernate.SQL: error
    org.hibernate.type.descriptor.sql.BasicBinder: off


cloudinary:
  cloud-name: ${CLOUDINARYNAME:deianov}
  api-key: ${CLOUDINARYKEY:113975441742847}
  api-secret: ${CLOUDINARYSECRET:}
  url: ${CLOUDINARY_URL}

myapp:
  version: 23.02.2022